name: obvious in retrospect.
title: obvious in retrospect.
description:  personal blog of jaseem m
meta_description: "personal blog of jaseem m about programming and time"
title_separator: '–'

about: false #'about.html'
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.mjaseem.com'
# google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate, jekyll-feed]
header: false #'/assets/images/header.jpg'
# Details for the RSS feed generator
url:            'www.mjaseem.com'
permalink: /:title:output_ext
# Site Author
author:
  name             : "Jaseem"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Programmer, wannabe renaissance man and all-around geek. I work as a developer and live in Bangalore, India"
  


defaults:

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      share: false